server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
    #timezone: Asia/Kolkata
    #timezone: America/Denver                                      
    
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
        # we can use the multiple controllerPath= /users/** ,/controllername/**
        
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/ratings/**  
        
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotels/**
        
#okta configuration for api gateway        
okta:
  oauth2:
    issuer: https://dev-32675440.okta.com/oauth2/default 
    audience: api://default
    client-id: 0oacm925icvP34MSY5d7
    client-secret: _XjSMavrqg8vui0kDYHPaWyMfMe2ydU9LRYXFzUqVMYGVRBVjTROjn0MA6ZZ6j5p
    scopes: openid, profile, email, offline_access